### ISSUE TITLE
Sample app crashes on start

### ISSUE THREAD

**Issue by miquelbeltran** [fluttercommunity/android_alarm_manager_plus#5]
## System info

Issue occurs on: Android
Plugin version: 0.4.6
Flutter doctor output:

```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_US.UTF-8)
    • Flutter version 1.17.5 at /home/miquel/dev/tools/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /home/miquel/Android/Sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Android Studio (version 4.0)
    • Android Studio at /home/miquel/.local/share/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • sdk gphone x86 • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

! Doctor found issues in 1 category.
```

## Steps to Reproduce

1. Run provided example app.

## Logs

```
2020-07-20 07:13:36.850 566-592/? I/ActivityManager: Start proc 7915:io.flutter.plugins.androidalarmmanagerexample/u0a157 for pre-top-activity {io.flutter.plugins.androidalarmmanagerexample/io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity}
2020-07-20 07:13:37.062 7915-7915/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.flutter.plugins.androidalarmmanagerexample, PID: 7915
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{io.flutter.plugins.androidalarmmanagerexample/io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity}: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity" on path: DexPathList[[zip file "/data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/base.apk"],nativeLibraryDirectories=[/data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/lib/x86, /data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3365)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "io.flutter.plugins.androidalarmmanagerexample.DriverExtensionActivity" on path: DexPathList[[zip file "/data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/base.apk"],nativeLibraryDirectories=[/data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/lib/x86, /data/app/~~WNvaAGQOC72qC2VdcfE7bw==/io.flutter.plugins.androidalarmmanagerexample-tKKPLz69z7o6y5FGXUQnzg==/base.apk!/lib/x86, /system/lib, /system_ext/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:41)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3353)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
2020-07-20 07:13:37.067 566-2868/? W/ActivityTaskManager:   Force finishing activity io.flutter.plugins.androidalarmmanagerexample/.DriverExtensionActivity
2020-07-20 07:13:37.117 566-1814/? I/ActivityManager: Process io.flutter.plugins.androidalarmmanagerexample (pid 7915) has died: prcp TOP 
```

**Comment by miquelbeltran** [comment]
Fixed on #6
